name: Release with Goreleaser

on:
  push:
    tags:
      - "v*"
jobs:
  goreleaser:
    strategy:
        matrix:
          go-version: [1.13.x]
          platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Print ref
      run: echo ${{ github.ref }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: goreleaser
      uses: goreleaser/goreleaser-action@master
      with:
        version: latest
        args: release --rm-dist
        key: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
