name: Test
on: push

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps: 
    - name: Print ref
      run: echo ${{ github.ref }} 
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      uses: cedrickring/golang-action@1.4.1
