on: [push, pull_request]

name: Release with Goreleaser

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    # - name: Install Go
    #   uses: actions/setup-go@v1
    #   with:
    #     go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      uses: cedrickring/golang-action@1.4.1


  goreleaser:
    strategy:
        matrix:
          go-version: [1.12.x, 1.13.x]
          platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    if: github.ref == 'refs/head/master'
    steps:
    - name: Checkout
        uses: actions/checkout@v2
    - name: Set up Go
        uses: actions/setup-go@v1
        with:
            go-version: 1.13.x

    - name: 
        uses: goreleaser/goreleaser-action@master
        with:
            version: latest
            args: release --rm-dist
            key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
