name: Test
on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps: 
    - name: Print ref
      run: echo ${{ github.ref }} 
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      uses: cedrickring/golang-action/go${{ matrix.go-version }}@1.4.1
